#!/usr/bin/env python3
"""
Upload character knowledge base to Pinecone for RAG retrieval.

This script processes JSONL knowledge base files generated by KnowledgeTool
and uploads them to Pinecone for semantic search.

Usage:
    python upload_to_pinecone.py --character "Jake Paul" --namespace "CHAR_xxxxx"
    python upload_to_pinecone.py --character "Jake Paul" --namespace "CHAR_xxxxx" --dry-run
    python upload_to_pinecone.py --list-namespaces
"""

import os
import json
import glob
import argparse
from pathlib import Path
from typing import Optional

# =========================
# Config - Update these or use environment variables
# =========================

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "sk-...")
PINECONE_API_KEY = os.environ.get("PINECONE_API_KEY", "pcsk_2Tq4uT_7usEkGyBaVqabTzndnqkfhEZhfMP3BtcR6N9Ht9sfs1NbgcaQc14mYeg2NPVrnb")

# Dev index by default
INDEX_NAME = os.environ.get("PINECONE_INDEX", "avatar-knowledge-te-3-large-256-dev")

# Default base path for character knowledge
DEFAULT_BASE_PATH = "/Users/justin-genies/Code/CharacterPrompts/Personas"

EMBED_MODEL = "text-embedding-3-large"
EMBED_DIM = 256


def setup_environment():
    """Set up environment variables for API access."""
    os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY


def get_pinecone_client():
    """Initialize and return Pinecone client and index."""
    from pinecone import Pinecone

    pc = Pinecone(api_key=PINECONE_API_KEY)
    index = pc.Index(INDEX_NAME)
    return pc, index


def get_embeddings():
    """Initialize and return OpenAI embeddings."""
    from langchain_openai import OpenAIEmbeddings

    return OpenAIEmbeddings(
        model=EMBED_MODEL,
        dimensions=EMBED_DIM
    )


def get_vector_store(index, embeddings):
    """Initialize and return Pinecone vector store."""
    from langchain_pinecone import PineconeVectorStore

    return PineconeVectorStore(
        index=index,
        embedding=embeddings
    )


def find_knowledge_files(character_name: str, base_path: str = DEFAULT_BASE_PATH) -> list[Path]:
    """Find all JSONL knowledge files for a character."""
    character_path = Path(base_path) / character_name / "Knowledge"

    if not character_path.exists():
        print(f"Knowledge directory not found: {character_path}")
        return []

    jsonl_files = list(character_path.glob("*.jsonl"))
    txt_files = list(character_path.glob("*.txt"))

    print(f"Found {len(jsonl_files)} JSONL files and {len(txt_files)} TXT files")
    return jsonl_files


def parse_jsonl_file(filepath: Path) -> list[dict]:
    """
    Parse a JSONL file and extract documents for embedding.

    Supports two JSONL formats:
    1. Video knowledge base format (from YouTube transcription):
       {"id":"t0-10","url":"...","title":"...","chunk_summary":"...","background":"...","text":"...","tags":[...]}

    2. Character memory format (from persona generation):
       {"id":"overview","section":"...","content":"...","keywords":[...]}
    """
    documents = []

    with open(filepath, 'r', encoding='utf-8') as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue

            try:
                entry = json.loads(line)

                # Determine format and extract content
                if 'content' in entry:
                    # Character memory format
                    doc = {
                        'id': entry.get('id', f'entry_{line_num}'),
                        'content': entry['content'],
                        'metadata': {
                            'source': str(filepath),
                            'section': entry.get('section', ''),
                            'keywords': entry.get('keywords', []),
                            'format': 'character_memory'
                        }
                    }
                elif 'text' in entry:
                    # Video knowledge base format
                    doc = {
                        'id': entry.get('id', f'entry_{line_num}'),
                        'content': entry['text'],
                        'metadata': {
                            'source': str(filepath),
                            'video_url': entry.get('url', ''),
                            'video_title': entry.get('title', ''),
                            'chunk_summary': entry.get('chunk_summary', ''),
                            'background': entry.get('background', ''),
                            'tags': entry.get('tags', []),
                            'format': 'video_knowledge'
                        }
                    }
                else:
                    # Unknown format - use entire JSON as content
                    doc = {
                        'id': f'entry_{line_num}',
                        'content': line,
                        'metadata': {
                            'source': str(filepath),
                            'format': 'raw'
                        }
                    }

                documents.append(doc)

            except json.JSONDecodeError as e:
                print(f"Warning: Failed to parse line {line_num} in {filepath}: {e}")
                continue

    return documents


def load_documents(character_name: str, base_path: str = DEFAULT_BASE_PATH) -> list:
    """Load all knowledge documents for a character."""
    from langchain.docstore.document import Document

    jsonl_files = find_knowledge_files(character_name, base_path)

    if not jsonl_files:
        print(f"No JSONL files found for character: {character_name}")
        return []

    all_docs = []

    for filepath in jsonl_files:
        print(f"Processing: {filepath.name}")
        parsed = parse_jsonl_file(filepath)

        for doc in parsed:
            langchain_doc = Document(
                page_content=doc['content'],
                metadata=doc['metadata']
            )
            all_docs.append(langchain_doc)

    print(f"Loaded {len(all_docs)} documents total")
    return all_docs


def list_namespace_ids(index, namespace: str, limit: int = 100) -> list[str]:
    """List all record IDs in a namespace."""
    try:
        # Use list endpoint to get IDs
        results = index.list(namespace=namespace, limit=limit)
        ids = []
        for id_list in results:
            if isinstance(id_list, list):
                ids.extend(id_list)
            else:
                ids.append(id_list)
        return ids
    except Exception as e:
        print(f"Error listing namespace: {e}")
        return []


def delete_namespace(index, namespace: str):
    """Delete all vectors in a namespace."""
    try:
        index.delete(delete_all=True, namespace=namespace)
        print(f"Deleted all vectors in namespace: {namespace}")
    except Exception as e:
        print(f"Error deleting namespace: {e}")


def upload_documents(
    character_name: str,
    namespace: str,
    base_path: str = DEFAULT_BASE_PATH,
    clear_existing: bool = False,
    dry_run: bool = False
):
    """Upload character knowledge documents to Pinecone."""
    setup_environment()

    # Load documents
    docs = load_documents(character_name, base_path)

    if not docs:
        print("No documents to upload")
        return

    if dry_run:
        print(f"\n=== DRY RUN ===")
        print(f"Would upload {len(docs)} documents to namespace: {namespace}")
        print(f"\nSample documents:")
        for i, doc in enumerate(docs[:3]):
            print(f"\n--- Document {i+1} ---")
            print(f"Content preview: {doc.page_content[:200]}...")
            print(f"Metadata: {doc.metadata}")
        return

    # Initialize Pinecone
    pc, index = get_pinecone_client()
    embeddings = get_embeddings()
    vector_store = get_vector_store(index, embeddings)

    # Optionally clear existing vectors
    if clear_existing:
        print(f"Clearing existing vectors in namespace: {namespace}")
        delete_namespace(index, namespace)

    # Generate IDs for documents
    ids = [f"{namespace}_{i}" for i in range(len(docs))]

    # Upload
    print(f"\nUploading {len(docs)} documents to namespace: {namespace}")
    vector_store.add_documents(
        documents=docs,
        ids=ids,
        namespace=namespace
    )

    print(f"Successfully uploaded {len(docs)} documents to namespace: {namespace}")


def list_available_characters(base_path: str = DEFAULT_BASE_PATH) -> list[str]:
    """List all characters with knowledge bases."""
    base = Path(base_path)
    characters = []

    for char_dir in base.iterdir():
        if char_dir.is_dir() and (char_dir / "Knowledge").exists():
            knowledge_dir = char_dir / "Knowledge"
            jsonl_count = len(list(knowledge_dir.glob("*.jsonl")))
            if jsonl_count > 0:
                characters.append((char_dir.name, jsonl_count))

    return characters


def main():
    parser = argparse.ArgumentParser(
        description="Upload character knowledge base to Pinecone",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Upload Jake Paul's knowledge to a specific namespace
  python upload_to_pinecone.py --character "Jake Paul" --namespace "CHAR_073ca002-fd77-4eaf-8745-d5381b8df005"

  # Dry run to see what would be uploaded
  python upload_to_pinecone.py --character "Jake Paul" --namespace "CHAR_test" --dry-run

  # Clear existing vectors before uploading
  python upload_to_pinecone.py --character "Jake Paul" --namespace "CHAR_test" --clear

  # List available characters
  python upload_to_pinecone.py --list-characters

  # Use production index
  python upload_to_pinecone.py --character "Jake Paul" --namespace "CHAR_xxx" --index avatar-knowledge-te-3-large-256-prod

Environment Variables:
  OPENAI_API_KEY     - OpenAI API key for embeddings
  PINECONE_API_KEY   - Pinecone API key
  PINECONE_INDEX     - Pinecone index name (default: avatar-knowledge-te-3-large-256-dev)
        """
    )

    parser.add_argument(
        "--character", "-c",
        type=str,
        help="Character name (folder name in Personas directory)"
    )

    parser.add_argument(
        "--namespace", "-n",
        type=str,
        help="Pinecone namespace (typically CHARACTER_ID)"
    )

    parser.add_argument(
        "--base-path", "-p",
        type=str,
        default=DEFAULT_BASE_PATH,
        help=f"Base path to Personas directory (default: {DEFAULT_BASE_PATH})"
    )

    parser.add_argument(
        "--index", "-i",
        type=str,
        help="Pinecone index name (overrides PINECONE_INDEX env var)"
    )

    parser.add_argument(
        "--clear",
        action="store_true",
        help="Clear existing vectors in namespace before uploading"
    )

    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be uploaded without actually uploading"
    )

    parser.add_argument(
        "--list-characters",
        action="store_true",
        help="List all characters with knowledge bases"
    )

    parser.add_argument(
        "--list-namespace",
        type=str,
        metavar="NAMESPACE",
        help="List all record IDs in a namespace"
    )

    args = parser.parse_args()

    # Override index if specified
    global INDEX_NAME
    if args.index:
        INDEX_NAME = args.index

    # Handle list-characters
    if args.list_characters:
        print(f"\nCharacters with knowledge bases in: {args.base_path}\n")
        characters = list_available_characters(args.base_path)
        if characters:
            for name, count in sorted(characters):
                print(f"  {name} ({count} JSONL files)")
        else:
            print("  No characters with JSONL knowledge files found")
        return

    # Handle list-namespace
    if args.list_namespace:
        setup_environment()
        pc, index = get_pinecone_client()
        print(f"\nListing records in namespace: {args.list_namespace}")
        ids = list_namespace_ids(index, args.list_namespace)
        print(f"Found {len(ids)} records:")
        for id in ids[:20]:
            print(f"  {id}")
        if len(ids) > 20:
            print(f"  ... and {len(ids) - 20} more")
        return

    # Validate required args for upload
    if not args.character:
        parser.error("--character is required for upload")

    if not args.namespace:
        parser.error("--namespace is required for upload")

    # Run upload
    upload_documents(
        character_name=args.character,
        namespace=args.namespace,
        base_path=args.base_path,
        clear_existing=args.clear,
        dry_run=args.dry_run
    )


if __name__ == "__main__":
    main()
